#ifndef __SDKCONFIG_H__
#define __SDKCONFIG_H__

#define CONFIG_LV_COLOR_DEPTH 16
#define CONFIG_BSP_DISPLAY_SPI_TRANS_QUEUE_DEPTH 2

#ifndef CONFIG_BSP_DISPLAY_SPI_CLOCK_HZ
    #define CONFIG_BSP_DISPLAY_SPI_CLOCK_HZ 40000000
#endif

#ifndef CONFIG_BSP_DISPLAY_SPI_MAX_TRANSFER_LINES
    #define CONFIG_BSP_DISPLAY_SPI_MAX_TRANSFER_LINES 10
#endif

#if !defined(BSP_TEST_TE_SYNC_UNDEFINED) && \
    !defined(CONFIG_BSP_DISPLAY_TE_SYNC)
    #define CONFIG_BSP_DISPLAY_TE_SYNC 1
#endif

#endif /* __SDKCONFIG_H__ */
